// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Ntdc4TgbgfAWXJmVtRCpaF33O4o3AMI',
    appId: '1:187106510701:web:b4b7ce899a1c9ffd2a7c64',
    messagingSenderId: '187106510701',
    projectId: 'cse331-a7e3b',
    authDomain: 'cse331-a7e3b.firebaseapp.com',
    databaseURL: 'https://cse331-a7e3b-default-rtdb.firebaseio.com',
    storageBucket: 'cse331-a7e3b.firebasestorage.app',
    measurementId: 'G-ZJXQVPZ757',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-KjfdBVcgHjkBzJpxYCf2G5NSCW_Epcc',
    appId: '1:187106510701:android:80fa676e9a3a6ead2a7c64',
    messagingSenderId: '187106510701',
    projectId: 'cse331-a7e3b',
    databaseURL: 'https://cse331-a7e3b-default-rtdb.firebaseio.com',
    storageBucket: 'cse331-a7e3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo4Kz8b3k41uH1q3Vy92gUSifJYytQa44',
    appId: '1:187106510701:ios:a7f3b68c781f52e32a7c64',
    messagingSenderId: '187106510701',
    projectId: 'cse331-a7e3b',
    databaseURL: 'https://cse331-a7e3b-default-rtdb.firebaseio.com',
    storageBucket: 'cse331-a7e3b.firebasestorage.app',
    iosBundleId: 'com.example.sentinelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo4Kz8b3k41uH1q3Vy92gUSifJYytQa44',
    appId: '1:187106510701:ios:a7f3b68c781f52e32a7c64',
    messagingSenderId: '187106510701',
    projectId: 'cse331-a7e3b',
    databaseURL: 'https://cse331-a7e3b-default-rtdb.firebaseio.com',
    storageBucket: 'cse331-a7e3b.firebasestorage.app',
    iosBundleId: 'com.example.sentinelapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3Ntdc4TgbgfAWXJmVtRCpaF33O4o3AMI',
    appId: '1:187106510701:web:08f521ec8075f9f42a7c64',
    messagingSenderId: '187106510701',
    projectId: 'cse331-a7e3b',
    authDomain: 'cse331-a7e3b.firebaseapp.com',
    databaseURL: 'https://cse331-a7e3b-default-rtdb.firebaseio.com',
    storageBucket: 'cse331-a7e3b.firebasestorage.app',
    measurementId: 'G-X7NLHJTM6J',
  );
}
